# Основной HTTPS-сервер
server {
    listen 80;
    listen 443;
    server_name artemii-kittygram.ddns.net;

    client_max_body_size 20M;

    # 1. В корне сайта отдаём собранный фронтенд Kittygram
    location / {
        root /home/ubuntu/infra_sprint1/frontend/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    # 2. Запросы к API перенаправляем в бэкенд Django Kittygram
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8080;
    }

    # 3. Админку Django тоже перенаправляем в бэкенд
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8080;
    }

    # 4. Статика бэкенда и фронтенда
    location /static/ {
        alias /home/ubuntu/infra_sprint1/frontend/build/static/;
    }

    # 5. Медиафайлы бэкенда
    location /media/ {
        alias /home/ubuntu/infra_sprint1/backend/media/;
    }

    # 6. Второй проект Taski на пути /taski/
    location /taski/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
    }
}
